### ISSUE TITLE
Visual Tools

### ISSUE THREAD

**Issue by BingHan0458** [Akash-Kumbar/TP-NoDe#2]
Hi Akash,

Thanks for the great work!
I would like to know what tool you used for visualizing point clouds in your paper? And what are the sources of some real datasets (such as Le Bassin d'Apollon, heritage data of Lord Nandi, carving of God Harihara) you use in your paper TP-NoDe and ASUR3D? Can you share it?
Thanks in advance!

Best,
Bing Han

**Comment by TejasAnvekar** [comment]
Hi Bing Han,

Thanks for showing interest in our work.
To render point clouds we use an opensource renderer "Mitsuba" 
code to render point clouds can be found [here](https://github.com/tolgabirdal/Mitsuba2PointCloudRenderer)
Regarding the real dataset was webscraped from sketchfab, and will be made public soon.

Best,
Tejas Anvekar
